package com.example.demo.Entity;

// ProfileEntity.java

import javax.persistence.*;

@Entity
@Table(name = "profiles")
public class ProfileEntity {

   
    @Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
private Long id;  // Remove the hardcoded value


    private String firstName;
    private String lastName;
   
    private int tournamentsAttended;
    private int tournamentsWon;
    private int tournamentsLoss;
    
    private String github;
    private String photo;
    private String location;
    private String rating;
   
    

    // Constructors, Getters, Setters, and other methods as needed

    // Constructors
    public ProfileEntity() {
        // Default constructor
    }

    public ProfileEntity(String firstName, String lastName, int tournamentsAttended,
                         int tournamentsWon, int tournamentsLoss, String github, String photo,
                         String location, String rating) {
        this.firstName = firstName;
        this.lastName = lastName;
       
        this.tournamentsAttended = tournamentsAttended;
        this.tournamentsWon = tournamentsWon;
        this.tournamentsLoss = tournamentsLoss;
        
        this.github = github;
        this.photo = photo;
        this.location = location;
        this.rating = rating;
                         }

    // Getters and Setters (generated by your IDE or written manually)

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

   
    public int getTournamentsAttended() {
        return tournamentsAttended;
    }

    public void setTournamentsAttended(int tournamentsAttended) {
        this.tournamentsAttended = tournamentsAttended;
    }

    public int getTournamentsWon() {
        return tournamentsWon;
    }

    public void setTournamentsWon(int tournamentsWon) {
        this.tournamentsWon = tournamentsWon;
    }

    public int getTournamentsLoss() {
        return tournamentsLoss;
    }

    public void setTournamentsLoss(int tournamentsLoss) {
        this.tournamentsLoss = tournamentsLoss;
    }

    

    public String getGithub() {
        return github;
    }

    public void setGithub(String github) {
        this.github = github;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getRating() {
        return rating;
    }

    public void setRating(String rating) {
        this.rating = rating;
    }

    
 
}
